# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('ppt_url_1', models.FileField(default='', max_length=1000, upload_to='')),
                ('ppt_url_2', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
                ('ppt_url_3', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
                ('ppt_url_4', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
                ('ppt_url_5', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
                ('ppt_url_6', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
            ],
        ),
    ]
