# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-05 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
