# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-07 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaAPI', '0003_auto_20190305_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='ImageAPI'),
        ),
    ]
