# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_imgdb_impath'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdb',
            name='impath',
            field=models.FileField(default='', max_length=1000, upload_to=''),
        ),
    ]
