# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_urls', models.FileField(blank=True, max_length=1000, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_1',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_2',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_3',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_4',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_5',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='doc_url_6',
        ),
        migrations.AddField(
            model_name='document_files',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docviewer.documents'),
        ),
    ]
